import MemoView from "@/components/memo/MemoView";
import MemoHeader from "@/components/memo/MemoHeader";
import MemoSection from "@/components/memo/MemoSection";
import KeyMetrics from "@/components/memo/KeyMetrics";
import BullBearCases from "@/components/memo/BullBearCases";
import SentimentLine from "@/components/memo/SentimentLine";
import MemoTable from "@/components/memo/MemoTable";

const MemoDemo = () => {
  return (
    <main className="min-h-screen pt-16 pb-32">
      <MemoView>
        <MemoHeader
          company="ITC Limited"
          ticker="NSE: ITC"
          sector="Consumer Defensive · Large Cap · NSE"
          recommendation="ACCUMULATE"
          metadata={[
            { label: "Date", value: "2026-05-04" },
            { label: "Classification", value: "PUBLIC EQUITIES" },
            { label: "Ticker", value: "NSE: ITC" },
            { label: "Distribution", value: "INTERNAL" },
            { label: "Sector", value: "Consumer Defensive" },
            { label: "Generated By", value: "MEMOAI v1.4" },
          ]}
        />

        <MemoSection number="01" label="Executive Summary">
          <p className="font-serif text-[17px] leading-[1.65] text-ink drop-cap">
            ITC Limited operates as a diversified Indian conglomerate with a
            durable franchise in cigarettes that funds aggressive capital
            deployment into FMCG, hotels, paperboards, and agribusiness.
            Cigarettes contribute roughly four-fifths of segment EBIT and
            generate exceptional capital efficiency, with leaf-procurement scale
            and distribution depth presenting structural barriers to entry. The
            FMCG segment has crossed an inflection on margins as
            premiumisation, route-to-market, and operating leverage compound.
          </p>
          <p className="font-serif text-[17px] leading-[1.65] text-ink mt-5">
            <span className="lead-in">Critical Limitation:</span> the planned
            demerger of the hotels business introduces near-term overhang and
            valuation arithmetic the market has not yet settled on. Our base
            case assumes a clean separation by Q3 FY27 with hotels trading at a
            structural premium to the parent.
          </p>
        </MemoSection>

        <MemoSection number="02" label="Key Metrics">
          <KeyMetrics
            metrics={[
              { label: "Market Cap", value: "₹5.7 L Cr" },
              { label: "P/E Ratio", value: "27.4x" },
              { label: "Revenue TTM", value: "₹76,840 Cr" },
              { label: "Net Margin", value: "27.8%" },
              { label: "ROE", value: "28.6%" },
              { label: "Debt/Equity", value: "0.02" },
            ]}
          />
        </MemoSection>

        <MemoSection number="03" label="Investment Thesis">
          <BullBearCases
            bull="FMCG segment EBIT margin expands from 9.1% to 12% by FY27 as premium SKUs scale and distribution depth converts to operating leverage. The hotels demerger trades at 25× EV/EBITDA on a normalised RevPAR cycle, releasing approximately ₹50,000 Cr of trapped value. Cigarette volumes hold flat against the illegal-trade crackdown, with mix-led pricing carrying revenue growth."
            bear="A GST compensation cess increase compresses cigarette EBIT margins by 200–300 bps without offsetting price elasticity. FMCG growth decelerates as urban discretionary spending tightens, deferring margin convergence to FY29. Hotel demerger lists at a discount to listed peers, leaving a structural conglomerate overhang on the parent."
          />
        </MemoSection>

        <MemoSection number="04" label="Sentiment">
          <SentimentLine label="Moderately Bullish" articles={47} />
        </MemoSection>

        <MemoSection number="05" label="Financial Profile">
          <MemoTable
            headers={["Metric", "FY22", "FY23", "FY24", "FY25E"]}
            rows={[
              ["Revenue (₹ Cr)", "60,645", "70,251", "73,108", "76,840"],
              ["EBITDA Margin", "34.2%", "35.7%", "36.9%", "37.4%"],
              ["Net Profit (₹ Cr)", "15,243", "18,753", "20,422", "21,375"],
              ["EPS (₹)", "12.37", "15.02", "16.34", "17.10"],
              ["Dividend Yield", "3.4%", "3.6%", "3.8%", "3.9%"],
              ["RoCE", "31.4%", "33.8%", "34.6%", "35.1%"],
            ]}
          />
        </MemoSection>

        <hr className="border-0 border-t border-rule mt-20 mb-6" />
        <p className="font-sans text-[12px] text-ink-muted leading-[1.6]">
          MemoAI generates research for informational purposes only. Not
          investment advice. All figures sourced from company filings and
          third-party data providers; verify independently before acting.
        </p>
      </MemoView>
    </main>
  );
};

export default MemoDemo;
