import type { MemoData } from "./MemoSearchForm";
import MemoView from "./memo/MemoView";
import MemoHeader, { Recommendation } from "./memo/MemoHeader";
import MemoSection from "./memo/MemoSection";
import KeyMetrics from "./memo/KeyMetrics";
import BullBearCases from "./memo/BullBearCases";
import SentimentLine from "./memo/SentimentLine";
import MemoMarkdown from "./MemoMarkdown";

interface MemoResultProps {
  company?: string;
  data?: MemoData;
}

const KNOWN_RECS: Recommendation[] = [
  "CONVICTION BUY",
  "ACCUMULATE",
  "HOLD",
  "MONITOR",
  "REDUCE",
];

const normalizeRecommendation = (rec: string): Recommendation => {
  const upper = rec.toUpperCase().trim();
  return (KNOWN_RECS.find((r) => upper.includes(r)) ?? "ACCUMULATE") as Recommendation;
};

const todayIso = () => new Date().toISOString().split("T")[0];

const buildMetadata = (
  ticker: string,
  sectorBlob: string,
  date = todayIso(),
) => {
  const sectorOnly = sectorBlob.split("·")[0]?.trim() || sectorBlob;
  return [
    { label: "Date", value: date },
    { label: "Classification", value: "PUBLIC EQUITIES" },
    { label: "Ticker", value: ticker || "—" },
    { label: "Distribution", value: "INTERNAL" },
    { label: "Sector", value: sectorOnly },
    { label: "Generated By", value: "MEMOAI v1.4" },
  ];
};

const SAMPLE_METRICS = [
  { label: "Market Cap", value: "$3.45T" },
  { label: "P/E Ratio", value: "33.2x" },
  { label: "Revenue TTM", value: "$394.3B" },
  { label: "Net Margin", value: "26.2%" },
  { label: "ROE", value: "147.2%" },
  { label: "Debt/Equity", value: "1.87" },
];

const MemoResult = ({ company, data }: MemoResultProps) => {
  const isLive = !!data?.content;
  const displayCompany = data?.company || company || "Apple Inc.";
  const tickerRaw = data?.ticker || (displayCompany.toLowerCase().includes("apple") ? "AAPL" : "");
  const tickerDisplay = tickerRaw
    ? tickerRaw.includes(":")
      ? tickerRaw
      : `NASDAQ: ${tickerRaw}`
    : "—";
  const sector = data?.sector || "Technology · Large Cap · NASDAQ";
  const recommendation = normalizeRecommendation(data?.recommendation ?? "Accumulate");
  const sentiment = data?.sentiment || "Moderately Bullish";

  return (
    <div className="mt-16">
      <MemoView>
        <MemoHeader
          company={displayCompany}
          ticker={tickerDisplay}
          sector={sector}
          recommendation={recommendation}
          metadata={buildMetadata(tickerDisplay, sector)}
        />

        {isLive ? (
          <div className="mt-16">
            <MemoMarkdown content={data!.content} />
          </div>
        ) : (
          <SampleBody sentiment={sentiment} />
        )}
      </MemoView>
    </div>
  );
};

function SampleBody({ sentiment }: { sentiment: string }) {
  return (
    <>
      <MemoSection number="01" label="Executive Summary">
        <p className="font-serif text-[17px] leading-[1.65] text-ink drop-cap">
          Apple Inc. demonstrates exceptional market positioning with sustained
          competitive advantages across hardware, software, and services
          ecosystems. The transition to a services-led revenue mix continues to
          drive structural margin expansion. Capital return remains best-in-
          class among mega-cap technology platforms.
        </p>
        <p className="font-serif text-[17px] leading-[1.65] text-ink mt-5">
          <span className="lead-in">Critical Limitation:</span> regulatory
          pressure across the EU and US on App Store economics introduces a
          near-term overhang. Our base case assumes negotiated outcomes that
          preserve roughly 70% of current take-rate.
        </p>
      </MemoSection>

      <MemoSection number="02" label="Key Metrics">
        <KeyMetrics metrics={SAMPLE_METRICS} />
      </MemoSection>

      <MemoSection number="03" label="Investment Thesis">
        <BullBearCases
          bull="Services revenue accelerates past 30% of total revenue, driving margin expansion to 50%+. AI integration across product lines creates a new super-cycle, with the installed base of two billion active devices providing exceptional distribution leverage."
          bear="Forced sideloading erodes App Store margins materially. China demand and supply chain tensions escalate, creating both revenue and cost pressure. Hardware upgrade cycle decelerates as AI features arrive on older silicon."
        />
      </MemoSection>

      <MemoSection number="04" label="Sentiment">
        <SentimentLine label={sentiment} articles={47} />
      </MemoSection>

      <hr className="border-0 border-t border-rule mt-20 mb-6" />
      <p className="font-sans text-[12px] text-ink-muted leading-[1.6]">
        MemoAI generates research for informational purposes only. Not
        investment advice. All figures sourced from company filings and
        third-party data providers; verify independently before acting.
      </p>
    </>
  );
}

export default MemoResult;
